### ISSUE TITLE
Unable to specify a custom filetype

### ISSUE THREAD

**Issue by danielshub** [islandoftex/arara#142]
I am unable to specify a custom file type. I am using version 6.1.0. I created an .araraconfig.yaml file that specifies a custom extension of "fig". I then call arara on a file called test.fig and get an error. Everything works fine if I call rename the file as test.tex. 

```
$ cat .araraconfig.yaml
!config

filetypes:
 - extension: fig
   pattern: ^\s//\s*
```

```
$ cat test.fig 
% arara: pdftex
% arara: clean: { extensions: [ log ] }
Hello world.
\bye
```
```
$ arara -vl test.fig
$ cat arara.log 
25 Jun 2021 16:18:08.661 ERROR - I could not find the provided file "test.fig" [ .tex | .dtx | .ltx | .drv | .ins ]. Please make sure the file exists and it has a valid extension.
25 Jun 2021 16:18:08.664 INFO  - Total: 0.09 seconds
```

**Comment by cereda** [comment]
Closed, as it was solved in https://gitlab.com/islandoftex/arara/-/issues/71 :wink:
