### ISSUE TITLE
log4j issue applying to arara?

### ISSUE THREAD

**Issue by sascha-andres** [islandoftex/arara#145]
At my company all machines are scanned for software "containing" the log4j vulnerability by searching for jar files containing JndiLookup.class. This highlights arara from within the tex live environment.

Is there any update planned or is this a coincidence and not using log4j at all?

**Comment by cereda** [comment]
Hi, thanks for the report!

The tool indeed uses `log4j` as logging framework. The Arch Linux packagers [notified us as well](https://gitlab.com/islandoftex/arara/-/issues/77). :wink: We bumped dependencies and generated a patch release. The new version is already installed in CTAN and hit (most of) the TL mirrors. So a package update might suffice (e.g, `tlmgr update arara` or through the GUI manager).

Hope that helps!

Cheerio!

**Comment by cereda** [comment]
As an addendum, I believe [Jonas' comment](https://bugs.archlinux.org/task/72996#comment204297) is spot on: an attack vector against `arara` would be explicitly running it on an untrusted TeX file.

**Comment by sascha-andres** [comment]
Thanks for the answer. I forward the link to our IT department as info and think that this will settle the issue

**Comment by cereda** [comment]
Awesome! Please poke us if further action or clarification is needed. :wink:

**Comment by longborough** [comment]
Greetings Brent’s friends,

It is with heavy heart that we wish to inform you
of the passing of our dear Brent,
yesterday 6th of December at 8am.

With a courageous and resolute determination
to fully live his life despite the 6-months diagnosis,
Brent far exceeded expectations, going on to live
almost 2 years.

He passed with Honour and Grace,
at home in our care, his family,
beside him until the very last minutes.

Should you wish to contact me, Celia,
my whatsapp number is 0044 7941 638386.

Thank you kindly,
Brent’s family
