### ISSUE TITLE
makeindex rule issue

### ISSUE THREAD

**Issue by marcdegraef** [islandoftex/arara#146]
Hi, 

I was using the makeindex rule (arara 6.0) and I believe there is an error on line 16:

        infile = base.concat('.').concat(input);

should be replaced by

        infile = base.concat('.').concat(input[0]);

Regards, Marc.

**Comment by cereda** [comment]
Hi Mark!

Ah, spot on, thanks! This issue sounded familiar, so I checked out our [CHANGELOG](https://gitlab.com/islandoftex/arara/-/blob/master/CHANGELOG.md#601-2021-03-30): we fixed that error in version 6.0.1. :wink: 

Speaking of which, you are running an old version of `arara` (given the report, I suspect 6.0.0), maybe you could update to the current version (6.1.5)? There's no incompatibility between them; matter of fact, there are actually some very important fixes. :wink: 

Typically, if you use TeX Live, `tlmgr update arara` would suffice (might require `sudo` depending on your install setup). We can help!

Thankfully, I have @TheTeXnician in the team, so we are way more active and organised than before. If you have any suggestions or feature requests, drop us a line. :wink: 

Cheerio!

Paulo

**Comment by TheTeXnician** [comment]
There has been no feedback here, so I'm closing this expecting it has been fixed by updating. Please reopen if this assessment is wrong.
