### ISSUE TITLE
Copy Command Bug

### ISSUE THREAD

**Issue by Nebabon** [islandoftex/arara#148]
I think there is a bug in the `copy` command where it is OS dependent. It seems to not account for the slashes (`/` and `\`). On a windows machine, the follow MWE fails.

I would suggest that this be updated to do be `/` and `\` independent so that it can be ported from Windows to Unix to Mac without issue. I am currently using arara to write a template for future thesis students.

```
% arara: pdflatex: { shell: yes , interaction: nonstopmode } 
% arara: copy: { files: [ 'main.pdf' ], target: '../test.pdf' }

\documentclass{report}

\begin{document}
This will work on a Windows machine:-- arara: copy: { files: [ 'main.pdf' ], target: '..\textbackslash test.pdf' }

This will fail on a Windows machine:-- arara: copy: { files: [ 'main.pdf' ], target: '../test.pdf' }

\end{document}```

**Comment by Nebabon** [comment]
<smacks head> I was worried I was posting on the wrong server...

Thanks for copying it over!

**Comment by cereda** [comment]
No worries, always a pleasure to help!

I've mirrored the issue here: https://gitlab.com/islandoftex/arara/-/issues/91

I will create a PR later on today, we will review and hopefully send it to CTAN in a day or two.

Thanks!

**Comment by cereda** [comment]
Version 7.0.4 sent to CTAN, should hit the mirrors in a couple of days. :tada:
