### ISSUE TITLE
Update readme to point to manual hosted on website

### ISSUE THREAD

**Issue by alihaiderismail** [islandoftex/arara#149]
The readme says
> You can read more about rules and directives in the user manual available in our [releases](https://gitlab.com/islandoftex/arara/-/releases) section

But as of [#60](https://github.com/islandoftex/arara/-/issues/60), the manual is no longer part of the releases section and is instead hosted on https://islandoftex.gitlab.io/arara/manual/. 

It would be very useful to update the readme to point to the appropriate location of the manual for new users. It took me a long time to find the hosted manual as the link to the website is also hard to find. It is only present in gitlab's repo project description and is otherwise not in the readme.

**Comment by cereda** [comment]
Thanks for the report, the `README` has been updated in the repository. :wink:
