### ISSUE TITLE
Consider a Move From rule

### ISSUE THREAD

**Issue by FLegendre** [islandoftex/arara#83]
Hi,

Thank a lot for your amazing work on arara.

Especially with beamer, one gets a lot of auxiliary files in the main directory when texing. One can use the "--output-directory" option on the command line to put all that stuff in a sub-directory when launching lualatex but it is cool to get the pdf file in the main directory. So I make a little arara rule "movefrom" used like this

```
% arara: lualatex: { options: "--output-directory=stuff" }
% arara: movefrom:   { items: [ pdf ], from: stuff }
\documentclass[11pt]{article}
\usepackage{fontspec}
\begin{document}
Hello word.
\end{document}
```

The yaml file "movefrom" is

```
!config
# Move From rule for arara
# requires arara 3.0+

identifier: movefrom
name: MoveFrom
command: <arara> @{isFalse(isEmpty(item), isWindows("cmd /c move /y ", "mv -f ").concat('"').concat(from).concat('/').concat(getBasename(file)).concat('.').concat(item).concat('"').concat(' .'))}
arguments:
- identifier: from
  flag: <arara> @{parameters.from}
```

Is it a good idea to put a rule like that in the arara distribution ?
## Happy texing,

François

**Comment by cereda** [comment]
Hi François, bonjour!

It is a good idea indeed! If fact, I am considering both `copy` and `move` rules. If I recall correctly, I added an optional  `required` flag for parameters in the rule scope specifically for this purpose. That way, we can ensure source and target are consistent. :wink: 

Thanks for the kind words and the awesome suggestion! I also apologize for the delay in shipping the new version, I have a thesis to write at the moment and it's driving me wackier than usual. :wink: 

All the best, pal!

Paulo

**Comment by TheTeXnician** [comment]
Version 6 will feature a [copy](https://gitlab.com/islandoftex/arara/-/blob/development/rules/arara-rule-copy.yaml) and a [move](https://gitlab.com/islandoftex/arara/-/blob/development/rules/arara-rule-move.yaml) rule, see https://gitlab.com/islandoftex/arara/-/issues/47#note_443223142.

**Comment by TheTeXnician** [comment]
arara v6 has been released and will make its way to CTAN within the next days.
